# Generated by Django 4.1 on 2022-08-20 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizza', '0003_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OrderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveBigIntegerField()),
                ('order_status', models.CharField(choices=[('accepted', 'Accepted'), ('process', 'In process'), ('ready', 'Ready')], default='accepted', max_length=16)),
                ('type_order', models.CharField(choices=[('restaurant', 'In a restaurant'), ('delivery', 'Delivery')], max_length=16)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('cart', 'Cart')], max_length=16)),
                ('payment_status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('process', 'In process')], default='In process', max_length=16)),
                ('order_item_drink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders', to='pizza.drink')),
                ('order_item_pizza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders', to='pizza.pizza')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(max_length=512)),
                ('pizza', models.ManyToManyField(to='pizza.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(max_length=512)),
                ('drink', models.ManyToManyField(to='pizza.drink')),
            ],
        ),
    ]
