# Generated by Django 4.1 on 2022-08-20 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_alter_pizza_weight_orderuser_orderpizza_orderdrink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderuser',
            name='order_item_drink',
        ),
        migrations.RemoveField(
            model_name='orderuser',
            name='order_item_pizza',
        ),
        migrations.AddField(
            model_name='orderdrink',
            name='order_item_drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders_drink', to='pizza.drink'),
        ),
        migrations.AddField(
            model_name='orderpizza',
            name='order_item_pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders_pizza', to='pizza.pizza'),
        ),
    ]
