# Generated by Django 4.1 on 2022-08-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_remove_orderdrink_order_item_drink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderuser',
            name='order_item_drink',
            field=models.ManyToManyField(related_name='user_orders', to='pizza.drink'),
        ),
        migrations.AlterField(
            model_name='orderuser',
            name='order_item_pizza',
            field=models.ManyToManyField(related_name='user_orders', to='pizza.pizza'),
        ),
    ]
