# Generated by Django 4.1 on 2022-08-20 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_alter_orderuser_order_item_drink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdrink',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='orderpizza',
            name='pizza',
        ),
        migrations.AddField(
            model_name='orderdrink',
            name='drink',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza.drink'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpizza',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza'),
            preserve_default=False,
        ),
    ]
